### PR TITLE
<bugfix: fixed and updated w/ monday item requests; pending real numb…

### PR DESCRIPTION
**Pull request by ronald-bbg**
…er phone validation>

## What type of PR is this? (check all applicable)

- [ ] Feature
- [x] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
See items to check from Monday ticket #: https://blackberg-group.monday.com/boards/1931719392/pulses/6215858800
All items addressed except REAL phone number validation - checking documentation sources for more information...

## Related Tickets & Documents
- Monday Task # 6215858800

## QA Instructions, Screenshots, Recordings
Check mobile to desktop breakpoints for form validation and progress bar experiences and any new copy listed in the monday ticket

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [x] Semantic HTML implemented?
- [x] Keyboard operability supported?
- [x] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _includes/form-registration/form-section1.html
 - _includes/form-registration/form-section2.html
 - _includes/form-registration/form-section3.html
 - _includes/form-registration/form-section4.html
 - _includes/form-registration/form-sectionC.html
 - _site/assets/css/styles.css
 - _site/assets/js/parsley-functions.js
 - _site/assets/sass/vha/pages/participant-registration/_index.scss
 - _site/participant-application/index.html
 - assets/css/styles.css
 - assets/js/parsley-functions.js
 - assets/sass/vha/pages/participant-registration/_index.scss
 - participant-application/index.html

### CODE REVIEW

**Comment by RyanCrux** [comment]
[#2 - Application page (mobile): first time going forward through application, pages 2-4 don't automatically go to application progress bar (confirmation did on both mobile and desktop).]

I was able to verify on my physical mobile device (iphone15 / brave browser and again in safari). Both times I was taken all the way up to the top for each new page. The experience on mobile was very smooth all the way though to the "thank you" screen ( I tested form validation as well). 

Please instruct further if more specific testing is required. I can look for other hardware devices laying around. My guess at this point is something was cached on Will's device from when we were having an issue with scrolling back to the top of the page last week?

**Comment by ronald-bbg** [comment]
Thanks, Ryan. It may have been a caching issue before we made the fixes. I verified no issues on my Samsung Galaxy. This could just be the use case so we can sign off on the mobile experience.

**Comment by will-bbg** [comment]
@ronald-bbg  @RyanCrux  Thanks for the testing. Let's discuss this more in our Monday sync.

**Review by will-bbg — CHANGES_REQUESTED** [review]
As discussed in our sync, for fields that are yes/no and require a description if yes is selected, please add an asterisk to the description field if yes is clicked on

As discussed in our sync, if this field is required but then switched to No, remove required state from description field
Screenshot 2024-03-11 at 8 25 07 AM
Screenshot 2024-03-11 at 8 25 01 AM

**Comment by will-bbg** [comment]
@ecstech-admin and @RyanCrux please review Ronald's PR

**Review by will-bbg — APPROVED** [review]

**Pull request merged**
