### PR TITLE
Feature/we 6041069693/landing page

### PR DESCRIPTION
**Pull request by will-bbg**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents
- Monday Task #6041069693
- Figma: https://www.figma.com/file/9BUbJaq9TOTtgqelqxyl2y/Veteran-Health-MIT-Hacking-Medicine-2024?type=design&node-id=0%3A1304&mode=design&t=bKQXXEJgXJLv4gG9-1

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [x] Semantic HTML implemented?
- [x] Keyboard operability supported?
- [x] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [x] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _includes/home/countdown.html
 - _includes/home/hackathon-application.html
 - _includes/home/hero.html
 - _includes/home/innovation-impact.html
 - _includes/home/interested-participants.html
 - _includes/home/introduction.html
 - _includes/home/strategic-focus.html
 - _includes/home/what-to-expect.html
 - _site/assets/img/home/deco-line-bottom.svg
 - _site/assets/img/home/deco-line-top.svg
 - _site/assets/img/home/decore-arrow-down.svg
 - _site/assets/img/home/hero-background.jpg
 - _site/assets/img/home/interested-participants.png
 - _site/assets/img/home/noise-bg.jpg
 - _site/assets/img/home/spaceship-alt.svg
 - _site/assets/img/home/strategic-focus.png
 - _site/assets/js/vendors/countdown/countdown.js
 - _site/assets/js/vendors/countdown/init.js
 - _site/assets/js/vendors/countdown/jquery.countdown.min.js
 - _site/assets/js/vendors/wavesjs/jquery.wavify.js
 - _site/assets/js/vendors/wavesjs/wavify.js
 - _site/assets/js/vendors/wavify/jquery.wavify.js
 - _site/assets/js/vendors/wavify/wavify.js
 - _site/assets/sass/vha/pages/home/contact-us.scss
 - _site/assets/sass/vha/pages/home/countdown.scss
 - _site/assets/sass/vha/pages/home/hackathon-application.scss
 - _site/assets/sass/vha/pages/home/hero.scss
 - _site/assets/sass/vha/pages/home/interested-participants.scss
 - _site/assets/sass/vha/pages/home/what-to-expect.scss
 - _site/participant-application/index.html
 - assets/img/home/deco-line-bottom.svg
 - assets/img/home/deco-line-top.svg
 - assets/img/home/hero-background.jpg
 - assets/img/home/interested-participants.png
 - assets/img/home/noise-bg.jpg
 - assets/img/home/spaceship-alt.svg
 - assets/img/home/strategic-focus.png
 - assets/js/vendors/countdown/countdown.js
 - assets/js/vendors/wavify/jquery.wavify.js
 - assets/js/vendors/wavify/wavify.js
 - assets/sass/vha/pages/home/countdown.scss
 - assets/sass/vha/pages/home/hackathon-application.scss
 - assets/sass/vha/pages/home/hero.scss
 - assets/sass/vha/pages/home/interested-participants.scss
 - assets/sass/vha/pages/home/what-to-expect.scss
 - .eleventyignore
 - _includes/form-registration/form-sectionTY.html
 - _site/assets/css/styles.css
 - _site/assets/js/functions.js
 - _site/assets/sass/vha/components/button/_index.scss
 - _site/assets/sass/vha/content/base.scss
 - _site/assets/sass/vha/content/images.scss
 - _site/assets/sass/vha/content/typography.scss
 - _site/assets/sass/vha/content/utilities.scss
 - _site/assets/sass/vha/pages/home/_index.scss
 - _site/index.html
 - _site/thank-you/index.html
 - assets/css/styles.css
 - assets/js/functions.js
 - assets/sass/vha/components/button/_index.scss
 - assets/sass/vha/content/base.scss
 - assets/sass/vha/content/images.scss
 - assets/sass/vha/content/typography.scss
 - assets/sass/vha/content/utilities.scss
 - assets/sass/vha/pages/home/_index.scss
 - index.html
 - thank-you/index.html
 - participant-application/index.html

### CODE REVIEW

**Review by ecstech-admin — COMMENTED** [review]
Grammar: comma after year on home page hero "May 17 - 19, 2024, at University of South Florida"

repo: rm /assets/fonts & _site/assets/fonts (used fonts are in assets/uswds/fonts)

deploy script: **/_site/coming-soon/** can be removed from exclude - this page doesn't exist in this repo

Application page (mobile): navigation for application steps reduced to lines (no numbers). Presume this is intended. Seems a bit odd with just 5 lines and no reference to what they are. Maybe add the word "progress" or "start....finish"

Application page (mobile): first time going forward through application, pages 2-4 don't automatically go to application progress bar (confirmation did on both mobile and desktop).

Using back button for correcting app data DOES automatically go to application progress bar

Application checking: doesn't check to make sure phone uses real number (1234567890 passed)

Required yes/no questions, but DON'T have to provide more details if you answer "yes" (eg: Logistics page, 3rd question)

Path to Thank you page needs to be corrected to: ../thank-you/
(currently, /ecosystem/views/veteran-health-mit-hacking-medicine-2024/thank-you)

Var data lost when you use fwd/back browser buttons. May want to state that at top: "Don't use forward/back buttons on your browser, content will be lost"

**Comment by will-bbg** [comment]
@ecstech-admin 

I've addressed the first three.

I'll create a ticket on monday and have Ronald address the issues on the form.

**Comment by ecstech-admin** [comment]
@will-bbg, edits look good. Will look out for other edits on this PR.

**Review by ecstech-admin — APPROVED** [review]
GTG

**Pull request merged**
